export const FETCH_STORIES_INIT = 'FETCH_STORIES:INIT';
export const FETCH_STORIES_SUCCESS = 'FETCH_STORIES:SUCCESS';
export const FETCH_STORIES_FAIL = 'FETCH_STORIES:FAIL';
export const STORIES_CLEAR_ALL = 'STORIES:CLEAR_ALL';
export const FETCH_COMMENTS_INIT = 'FETCH_COMMENTS:INIT';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS:SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS:FAIL';
